#!/bin/bash

if [ $# -eq 0 ]; then
    NAMESERVERS=("nameserver 178.22.122.100\nnameserver 185.51.200.2" "nameserver 10.202.10.202\nnameserver 10.202.10.102" "nameserver 1.1.1.1\nnameserver 1.0.0.1" "nameserver 8.8.8.8\nnameserver 8.8.4.4" "nameserver 10.202.10.10\nnameserver 10.202.10.11")
    NAMESERVER=$(printf '%s\n' "${NAMESERVERS[@]}" | wofi -c "$HOME/.config/wofi/config_2" --dmenu -k /dev/null -W 400 -r "echo '%s' | grep -o '[0-9. ]*' | tr -d '\n'")
    if [ -n "$NAMESERVER" ]; then
        echo -e "$NAMESERVER" | sudo tee /etc/resolv.conf
    fi
else
    cat /etc/resolv.conf | grep -oE '[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+'
fi

