#!/bin/bash
echo -e "$(hyprctl -j devices)" | gojq -r '.keyboards | .[] | select(.main == true) | .active_keymap' | cut -c 1-3
# echo -e "$(hyprctl -j devices)" | gojq -r '.keyboards | .[] | select(.name == "telink-wireless-receiver") | .active_keymap' | cut -c 1-3
