#!/bin/bash

status=$(nmcli -t -f DEVICE,STATE con show --active)

if echo "$status" | grep -q "enp"; then
    icon="󰈀"
    text=""
    col="#13d49a"
elif echo "$status" | grep -q "wl"; then
    icon="󰖩"
    text="$(iwgetid -r)"
    col="#13d49a"
else
    icon="󰖪"
    text=""
    col="#e75050"
fi

if [[ "$1" == "--COL" ]]; then
    echo $col
elif [[ "$1" == "--ESSID" ]]; then
    echo $text
elif [[ "$1" == "--ICON" ]]; then
    echo $icon
elif [[ "$1" == "--LIST" ]]; then
    notify-send -t 0 "Please wait..." "Getting available Wi-Fi networks list"
    # Get a list of available wifi connections and morph it into a nice-looking list
    wifi_list=$(nmcli --fields SSID,SECURITY,RATE,BARS device wifi list | sed '/^--/d' | sed 1d | sed -E "s/WPA*.?\S/~~/g" | sed -E "s/WEP*.?\S/~~/g" |  sed "s/~~ ~~/~~/g;s/802\.1X//g;s/--/~~/g;s/  *~/~/g;s/~  */~/g;s/_/ /g" | column -t -s '~')

    connected=$(nmcli -fields WIFI g)
    if [[ "$connected" =~ "enabled" ]]; then
        toggle="睊  Disable Wi-Fi"
    elif [[ "$connected" =~ "disabled" ]]; then
        toggle="直  Enable Wi-Fi"
    fi

    $(killall dunst)

    # Use rofi to select wifi network
    chosen_network=$(echo -e "$toggle\n$wifi_list" | uniq -u | wofi -c "$HOME/.config/wofi/config_2" -d -L 6)
    # Get name of connection
    chosen_id=$(echo "$chosen_network" | awk -F'' '{print $1}' | xargs)


    if [ "$chosen_network" = "" ]; then
        exit
    elif [ "$chosen_network" = "直  Enable Wi-Fi" ]; then
        nmcli radio wifi on
    elif [ "$chosen_network" = "睊  Disable Wi-Fi" ]; then
        nmcli radio wifi off
    else
        # Message to show when connection is activated successfully
        success_message="You are now connected to the Wi-Fi network \"$chosen_id\"."
        # Get saved connections
        saved_connections=$(nmcli -g NAME connection)
        if [[ $(echo "$saved_connections" | grep -w "$chosen_id") = "$chosen_id" ]]; then
            nmcli connection up id "$chosen_id" | grep "successfully" && notify-send "Connection successfully" "$success_message"
        else
            if [[ "$chosen_network" =~ "" ]]; then
                wifi_password=$(wofi -d -P)
            fi
            nmcli device wifi connect "$chosen_id" password "$wifi_password" | grep "successfully" && notify-send "Connection successfully" "$success_message"
        fi
    fi
fi
