#!/bin/bash

if [ $# -eq 0 ]; then

    if pgrep swayidle &> /dev/null; then
        killall swayidle
    else
        bash ~/.config/hypr/screensaver &
    fi
else
    if pgrep swayidle &> /dev/null; then
        echo "󰾩"
    else
        echo "󱡦"
    fi
fi


