#!/usr/bin/env sh
HYPRGAMEMODE=$(hyprctl getoption animations:enabled | sed -n '2p' | awk '{print $2}')
if [ $HYPRGAMEMODE = 1 ] ; then
    killall eww 2>/dev/null
    hyprctl --batch "\
        keyword animations:enabled 0;\
        keyword decoration:drop_shadow 0;\
        keyword decoration:blur 0;\
        keyword general:gaps_in 0;\
        keyword general:gaps_out 0;\
        keyword general:border_size 0;\
        keyword decoration:rounding 0;\
        keyword decoration:inactive_opacity 1;\
        keyword decoration:shadow_range 0;\
        keyword decoration:dim_inactive 0"
    exit
fi
hyprctl reload
eww daemon && eww open bar
